spring:
  application:
    name: ${MTS_APP_NAME:online-shop}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  liquibase:
    enabled: ${MTS_LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${MTS_DB_USERNAME:user}
    password: ${MTS_DB_PASSWORD:pass}
  jta:
    enabled: true
    transaction-manager-id: narayana-transaction-manager
    allow-custom-isolation-levels: true
    default-transaction-timeout: 300
    narayana:
      log-dir: ./target/tx-object-store
      node-identifier: mts-online-shop
      periodic-recovery-period: 120
      recovery-backoff-period: 10
      status-port: 4712
      socket-process-id-port: 4713
      socket-process-id-max-ports: 10
      xa-resource-orphan-filters:
        - com.arjuna.ats.internal.jta.recovery.arjunacore.JTATransactionLogXAResourceOrphanFilter
        - com.arjuna.ats.internal.jta.recovery.arjunacore.JTANonXAResourceOrphanFilter
        - com.arjuna.ats.jta.recovery.SerializableXAResourceOrphanFilter
  mail:
    host: ${MTS_MAIL_HOST:smtp.mail.ru}
    port: ${MTS_MAIL_PORT:465}
    username: ${MTS_MAIL_USERNAME:noreply@localhost}
    password: ${MTS_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

server:
  port: ${MTS_PORT:8080}
  servlet:
    context-path: ${MTS_CONTEXT_PATH:/api}

jwt:
  secret: ${MTS_JWT_SECRET:s9/PnuqMovO16uMBoWSjwoWI8etyn1KLFvfCLyTXq+g=}
  expiration-ms: ${MTS_JWT_EXPIRATION_MS:1800000}

bank:
  base-url: ${BANK_URL:http://localhost:8081}

logging:
  level:
    root: ${MTS_LOG_LEVEL:INFO}
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO

mail:
  from: ${MTS_MAIL_USERNAME:noreply@localhost}