---
config:
  layout: elk
---
flowchart LR
 subgraph Controllers["Web / API Layer"]
    direction TB
        OrderController["OrderController"]
        GoodsController["GoodsController"]
  end
 subgraph Services["Service Layer"]
    direction TB
        OrderService["OrderService"]
        GoodsService["GoodsService"]
        OrderMapper["OrderMapper"]
        BankSimulator["BankSimulator"]
        MailSimulator["MailSimulator"]
  end
 subgraph Repositories["Repository Layer"]
    direction TB
        OrderRepository["OrderRepository"]
        GoodsRepository["GoodsRepository"]
        UserItemRepository["UserItemRepository"]
        UserRepository["UserRepository"]
  end
 subgraph Entities["Domain / Entity Layer"]
    direction TB
        Order["Order"]
        OrderItem["OrderItem"]
        User["User"]
        UserItem["UserItem"]
        Product["Product"]
        OrderStatus["OrderStatus"]
  end
    OrderController --> OrderService
    GoodsController --> GoodsService
    OrderService --> OrderRepository & GoodsService & OrderMapper & BankSimulator & MailSimulator
    GoodsService --> GoodsRepository & UserItemRepository & UserRepository
    OrderRepository --> Order
    UserItemRepository --> UserItem
    GoodsRepository --> Product
    UserRepository --> User
    OrderMapper --> Order & OrderItem
    Order --> OrderItem & User & OrderStatus
    OrderItem --> Product
    UserItem --> User & Product